version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn CopyCentral_Hub.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/CopyCentral_Hub/web/staticfiles
      - media_volume:/home/CopyCentral_Hub/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/CopyCentral_Hub/web/staticfiles
      - media_volume:/home/CopyCentral_Hub/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: