version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers=2 CopyCentral_Hub.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/CopyCentral_Hub/web/staticfiles
      - media_volume:/home/CopyCentral_Hub/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    restart: always
    image: tomasz987/biuroserwis_web:latest

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/CopyCentral_Hub/web/staticfiles
      - media_volume:/home/CopyCentral_Hub/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    image: tomasz987/biuroserwis_nginx:latest


volumes:
  postgres_data:
  static_volume:
  media_volume:
